### ISSUE TITLE
feat: rate modifiers and rules

### ISSUE THREAD

**Issue by lucarioams** [windingtree/lpms-server#26]
For implementing this, we require:

- [x] windingtree/win-stays#99
- [x] #45
- [x] #46

**Comment by mfw78** [comment]
This is complete, with the exception of the tax information. As we take that all the prices quoted are going to be inclusive of all applicable taxes (excluding those that are levied at the point of arrival) - then any tax information here would be for 'guidance' / transparency purposes, which is more of a question for the `stays-models` (ie. `Facility` metadata).
